"""Curated kink catalog — categorized, deduplicated, ordered vanilla -> edge.

Source of truth for the questionnaire seeded into every new profile. Each entry
is a (label, description) tuple. The category list itself is ordered from most
common/vanilla at the top to most edge at the bottom. Items within a category
are roughly ordered by how widely-known/popular they are (most common first).

The legacy `Kinks.csv` file is left alone in the project root for reference,
but `kink_library.list_kinks()` no longer reads it — this module is canonical.

When adding new items: clarify any unclear label (e.g. "69" -> "69 (mutual
oral)"), avoid duplicates across categories, and place at the top of the
category if it's broadly known, bottom if it's edge.
"""

from __future__ import annotations

import re
from typing import NamedTuple


class CatalogEntry(NamedTuple):
    label: str
    description: str = ""


class CatalogCategory(NamedTuple):
    id: str
    label: str
    description: str
    items: list[CatalogEntry]


# Order matters: this is display order, vanilla at top, edge at bottom.
CATEGORIES: list[CatalogCategory] = [
    CatalogCategory(
        id="affection_romance",
        label="Affection & Romance",
        description="The connective tissue of intimacy: closeness, attention, and care. Most people rate something here highly even before anything sexual is on the table.",
        items=[
            CatalogEntry("Kissing"),
            CatalogEntry("Making out"),
            CatalogEntry("Cuddling"),
            CatalogEntry("Cuddling naked"),
            CatalogEntry("Snuggling"),
            CatalogEntry("Touching", "Non-sexual touch — back, hands, hair."),
            CatalogEntry("Caressing"),
            CatalogEntry("Eye contact"),
            CatalogEntry("Forehead kisses"),
            CatalogEntry("Neck kissing / touching"),
            CatalogEntry("Tongue sucking", "Slow, lingering tongue-on-tongue kissing."),
            CatalogEntry("Showering together"),
            CatalogEntry("Affection", "General warm physical/verbal affection."),
            CatalogEntry("Aftercare", "Post-scene care: cuddling, water, talking it through."),
            CatalogEntry("Flirting"),
            CatalogEntry("Seduction"),
            CatalogEntry("Teasing"),
            CatalogEntry("Humor", "Playful banter and laughter as part of intimacy."),
            CatalogEntry("Trust"),
            CatalogEntry("Honesty"),
            CatalogEntry("Love"),
            CatalogEntry("Attention", "Receiving focused attention from a partner."),
            CatalogEntry("Sapiosexuality", "Intelligence as a primary attractor."),
            CatalogEntry("Monogamy", "One-partner relationship style."),
            CatalogEntry("Cuddling that may become sex"),
        ],
    ),
    CatalogCategory(
        id="sex_positions",
        label="Sex & Positions",
        description="Vanilla and near-vanilla sexual acts. The bread and butter for most people.",
        items=[
            CatalogEntry("Vaginal sex"),
            CatalogEntry("Oral sex (general)"),
            CatalogEntry("Cunnilingus", "Oral on a vulva."),
            CatalogEntry("Blowjobs", "Oral on a penis."),
            CatalogEntry("69 (mutual oral)", "Both partners performing oral simultaneously, head-to-foot."),
            CatalogEntry("Anal sex"),
            CatalogEntry("Anal play", "Non-penetrative anal touching, fingering, light play."),
            CatalogEntry("Anal fingering"),
            CatalogEntry("Rimming / analingus", "Oral-anal contact."),
            CatalogEntry("Ass licking"),
            CatalogEntry("Ass play"),
            CatalogEntry("Ass-to-mouth (A2M)"),
            CatalogEntry("Fingering"),
            CatalogEntry("Handjobs"),
            CatalogEntry("Tit fucking"),
            CatalogEntry("Pegging", "Receiving anal sex from a partner with a strap-on."),
            CatalogEntry("Doggy style"),
            CatalogEntry("Face sitting / smothering"),
            CatalogEntry("Queening", "Sitting on a partner's face."),
            CatalogEntry("Mutual masturbation"),
            CatalogEntry("Masturbation"),
            CatalogEntry("Morning sex"),
            CatalogEntry("Shower sex"),
            CatalogEntry("Outdoor sex"),
            CatalogEntry("Sleepy sex", "Slow sex with a drowsy partner; both consenting."),
            CatalogEntry("Waking up to oral sex"),
            CatalogEntry("Bareback", "Sex without a condom."),
            CatalogEntry("Tearing off clothing"),
            CatalogEntry("Rough sex"),
            CatalogEntry("Multiple orgasms"),
            CatalogEntry("Wrestling", "Playful or erotic wrestling."),
            CatalogEntry("Road head", "Oral sex while driving (in a parked or moving car)."),
            CatalogEntry("Deep throating"),
            CatalogEntry("Throat fucking"),
            CatalogEntry("Face fucking"),
            CatalogEntry("Gagging on cock"),
            CatalogEntry("Double penetration"),
            CatalogEntry("Triple penetration"),
        ],
    ),
    CatalogCategory(
        id="body_appreciation",
        label="Body Appreciation",
        description="Bodies and looks — features, types, and aesthetics that turn you on.",
        items=[
            CatalogEntry("Breasts"),
            CatalogEntry("Big tits"),
            CatalogEntry("Small tits"),
            CatalogEntry("Hands"),
            CatalogEntry("Legs"),
            CatalogEntry("Feet"),
            CatalogEntry("Toes"),
            CatalogEntry("Necks"),
            CatalogEntry("Tongues"),
            CatalogEntry("Hair (general)"),
            CatalogEntry("Long hair"),
            CatalogEntry("Pubic hair"),
            CatalogEntry("Body hair"),
            CatalogEntry("Beards"),
            CatalogEntry("Facial hair"),
            CatalogEntry("Bald partners"),
            CatalogEntry("Pigtails"),
            CatalogEntry("Freckles"),
            CatalogEntry("Glasses"),
            CatalogEntry("Older men"),
            CatalogEntry("Older women"),
            CatalogEntry("Red heads"),
            CatalogEntry("Goth aesthetic"),
            CatalogEntry("Geek / nerd partners"),
            CatalogEntry("Butches", "Masculine-presenting partners."),
            CatalogEntry("Muscles"),
            CatalogEntry("Androgyny"),
            CatalogEntry("Bisexuality", "Bi-attraction or bi-roleplay."),
            CatalogEntry("Pregnancy", "Attraction to pregnant partners."),
            CatalogEntry("BBW", "Big Beautiful Women — full-figured female partners."),
            CatalogEntry("BBW / BHM", "Plus-size partners of any gender."),
            CatalogEntry("Tattoos"),
            CatalogEntry("Piercings"),
            CatalogEntry("Genital piercings"),
            CatalogEntry("Nipple piercings"),
            CatalogEntry("Body modification"),
            CatalogEntry("Shaving", "Shaved body hair as aesthetic."),
            CatalogEntry("Head shaving", "Shaved head as aesthetic or scene element."),
            CatalogEntry("Uncut cock"),
            CatalogEntry("Large labia"),
            CatalogEntry("Nudity"),
            CatalogEntry("Armpits", "Axillary fetish — armpits as an erotic feature."),
            CatalogEntry("Barefoot"),
            CatalogEntry("Braces", "Dental braces as a fetish feature."),
            CatalogEntry("Blushing", "Arousal at seeing a partner blush."),
        ],
    ),
    CatalogCategory(
        id="sensual_play",
        label="Sensual Play",
        description="Light sensation that's about texture, build-up, and finesse rather than force.",
        items=[
            CatalogEntry("Erotic massage"),
            CatalogEntry("Massage"),
            CatalogEntry("Hot oil massage"),
            CatalogEntry("Foot massage"),
            CatalogEntry("Sensual play (general)"),
            CatalogEntry("Sensation play (general)"),
            CatalogEntry("Hair pulling"),
            CatalogEntry("Biting"),
            CatalogEntry("Neck biting"),
            CatalogEntry("Pinching"),
            CatalogEntry("Scratching"),
            CatalogEntry("Tickling"),
            CatalogEntry("Feathers"),
            CatalogEntry("Ice cubes"),
            CatalogEntry("Fur", "Fur as a texture against skin."),
            CatalogEntry("Edging", "Building toward orgasm without release."),
            CatalogEntry("Talking dirty"),
            CatalogEntry("Voice play"),
            CatalogEntry("Auralism", "Arousal from sounds and voices."),
            CatalogEntry("Accents", "Arousal from a particular accent or dialect."),
            CatalogEntry("Whispering"),
            CatalogEntry("Blindfolds"),
            CatalogEntry("Sensory deprivation"),
            CatalogEntry("Pressure points"),
            CatalogEntry("Scent", "Partner's scent as an erotic cue."),
            CatalogEntry("Licking"),
            CatalogEntry("Long fingernails", "Fingernails as a sensation tool."),
            CatalogEntry("Food play"),
            CatalogEntry("Chocolate", "Chocolate as part of food play."),
            CatalogEntry("Liquor / alcohol play", "Alcohol used as part of a scene; consent and safety first."),
            CatalogEntry("Smoking", "Smoking as an aesthetic / scene element."),
            CatalogEntry("Cigars", "Cigar smoking fetish."),
            CatalogEntry("Bellydancing", "Watching or performing belly dance."),
            CatalogEntry("Nyotaimori", "Food (e.g. sushi) served on a body."),
            CatalogEntry("Grooming", "Doing a partner's hair, makeup, dressing them as a scene element."),
            CatalogEntry("Claws", "Long fingernails or costume claws as a sensation tool."),
        ],
    ),
    CatalogCategory(
        id="apparel_costumes",
        label="Apparel & Costumes",
        description="What you and your partner wear — fabrics, fetish wear, and dressing-up.",
        items=[
            CatalogEntry("Lingerie"),
            CatalogEntry("Vintage lingerie"),
            CatalogEntry("Stockings / pantyhose"),
            CatalogEntry("Fishnets"),
            CatalogEntry("Knee-high socks"),
            CatalogEntry("Socks"),
            CatalogEntry("High heels"),
            CatalogEntry("Boots", "Boot fetish."),
            CatalogEntry("Shoes", "Shoe fetish (retifism)."),
            CatalogEntry("Ballet boots / shoes"),
            CatalogEntry("Corsets"),
            CatalogEntry("Corset cinching"),
            CatalogEntry("Corset training"),
            CatalogEntry("Lace"),
            CatalogEntry("Silk"),
            CatalogEntry("Velvet"),
            CatalogEntry("Satin"),
            CatalogEntry("Spandex / lycra"),
            CatalogEntry("Catsuits"),
            CatalogEntry("Latex"),
            CatalogEntry("Leather"),
            CatalogEntry("Rubber"),
            CatalogEntry("PVC"),
            CatalogEntry("Vinyl"),
            CatalogEntry("Denim"),
            CatalogEntry("Body paint"),
            CatalogEntry("Lipstick"),
            CatalogEntry("Makeup"),
            CatalogEntry("Skirts"),
            CatalogEntry("Petticoats"),
            CatalogEntry("Panties"),
            CatalogEntry("Kilts"),
            CatalogEntry("Chaps"),
            CatalogEntry("Gloves"),
            CatalogEntry("Uniforms (general)"),
            CatalogEntry("Military uniforms"),
            CatalogEntry("Cheerleading uniforms"),
            CatalogEntry("Business suits"),
            CatalogEntry("Costumes / dressing-up"),
            CatalogEntry("Fetish wear (general)"),
            CatalogEntry("Nylon legs & feet"),
        ],
    ),
    CatalogCategory(
        id="roleplay_scenarios",
        label="Roleplay Scenarios",
        description="Played-out scenes with characters and a setup. Mostly playful; the heavier scenarios live in the Taboo category at the bottom.",
        items=[
            CatalogEntry("Roleplay (general)"),
            CatalogEntry("Cosplay"),
            CatalogEntry("Boss / secretary"),
            CatalogEntry("Doctor / nurse"),
            CatalogEntry("Teacher / student"),
            CatalogEntry("Schoolgirl"),
            CatalogEntry("French maid"),
            CatalogEntry("Librarian"),
            CatalogEntry("Geisha"),
            CatalogEntry("Pirates"),
            CatalogEntry("Vampires"),
            CatalogEntry("Superheroes"),
            CatalogEntry("Robots"),
            CatalogEntry("Steampunk"),
            CatalogEntry("Damsel in distress"),
            CatalogEntry("Nun / priest"),
            CatalogEntry("Military"),
            CatalogEntry("Interrogation", "Scene-style questioning with a captor / captive frame."),
            CatalogEntry("Medical play", "Scenes with medical equipment, exams, etc."),
            CatalogEntry("Martial arts"),
            CatalogEntry("Clowns", "Clown-themed roleplay."),
        ],
    ),
    CatalogCategory(
        id="multi_partner_group",
        label="Multi-Partner & Group",
        description="Anything with more than two participants, or stories involving outside partners.",
        items=[
            CatalogEntry("Threesomes"),
            CatalogEntry("FMF threesomes"),
            CatalogEntry("MMF threesomes"),
            CatalogEntry("Two-girl blowjobs"),
            CatalogEntry("Group sex"),
            CatalogEntry("Orgy"),
            CatalogEntry("Gangbangs"),
            CatalogEntry("Bukkake"),
            CatalogEntry("Polyamory"),
            CatalogEntry("Swinging"),
            CatalogEntry("Cuckolding", "Watching one's partner with someone else, by arrangement."),
            CatalogEntry("Hotwife", "Married woman taking outside partners with her partner's blessing."),
            CatalogEntry("Anonymous encounters"),
            CatalogEntry("Sex with strangers"),
            CatalogEntry("Infidelity fantasy", "Fictional cheating scenarios — fantasy only."),
            CatalogEntry("BBC", "Big Black Cock fantasy — typically a cuckold/hotwife frame."),
            CatalogEntry("Interracial sex"),
        ],
    ),
    CatalogCategory(
        id="voyeurism_exhibitionism",
        label="Voyeurism & Exhibitionism",
        description="Watching, being watched, and recording — public or via media.",
        items=[
            CatalogEntry("Exhibitionism"),
            CatalogEntry("Voyeurism"),
            CatalogEntry("Public play"),
            CatalogEntry("Flashing"),
            CatalogEntry("Glory hole"),
            CatalogEntry("Cybersex / online play"),
            CatalogEntry("Phone sex"),
            CatalogEntry("Sexting"),
            CatalogEntry("Webcams"),
            CatalogEntry("Photography"),
            CatalogEntry("Erotic photography"),
            CatalogEntry("Making home movies"),
            CatalogEntry("Porn"),
            CatalogEntry("Vintage porn"),
            CatalogEntry("Hentai"),
            CatalogEntry("Anime"),
            CatalogEntry("Erotic literature"),
            CatalogEntry("Writing erotica"),
            CatalogEntry("Erotic art"),
            CatalogEntry("Bondage art"),
            CatalogEntry("Pin-ups"),
            CatalogEntry("Burlesque"),
            CatalogEntry("Fetish models"),
            CatalogEntry("CFNM", "Clothed Female, Nude Male."),
            CatalogEntry("Wearing butt plug in public"),
            CatalogEntry("No-panties rule", "Going out with no underwear under regular clothes."),
        ],
    ),
    CatalogCategory(
        id="power_exchange",
        label="Power Exchange & D/s",
        description="Authority dynamics — leading, surrendering, and the structures around them.",
        items=[
            CatalogEntry("Power exchange"),
            CatalogEntry("D/s", "Dominant / submissive dynamic."),
            CatalogEntry("Domination"),
            CatalogEntry("Submission"),
            CatalogEntry("Switching", "Shifting between dominant and submissive sides."),
            CatalogEntry("FemDom", "Female-led dominance."),
            CatalogEntry("Female supremacy"),
            CatalogEntry("Male authority"),
            CatalogEntry("Male submission"),
            CatalogEntry("Pro Domme", "Professional dominant."),
            CatalogEntry("Brats", "Submissive who playfully resists."),
            CatalogEntry("Master / slave"),
            CatalogEntry("Service", "Submission expressed through useful tasks."),
            CatalogEntry("Service-oriented submission"),
            CatalogEntry("Domestic discipline"),
            CatalogEntry("Domestic servitude"),
            CatalogEntry("Discipline (general)"),
            CatalogEntry("Behavior modification"),
            CatalogEntry("Obedience training"),
            CatalogEntry("Protocol"),
            CatalogEntry("High protocol"),
            CatalogEntry("Affectionate domination"),
            CatalogEntry("Affectionate cruelty"),
            CatalogEntry("Sensual domination"),
            CatalogEntry("Subspace", "The deep submissive headspace."),
            CatalogEntry("Begging"),
            CatalogEntry("Crawling"),
            CatalogEntry("Kneeling"),
            CatalogEntry("Cornertime"),
            CatalogEntry("Eye contact restrictions"),
            CatalogEntry("Speech restriction"),
            CatalogEntry("Bathroom-use control"),
            CatalogEntry("Enforced bedtime"),
            CatalogEntry("Ordered to masturbate"),
            CatalogEntry("Tease & denial"),
            CatalogEntry("Orgasm control"),
            CatalogEntry("Orgasm denial"),
            CatalogEntry("Chastity", "Restricted access to one's own genitals (often via a device)."),
            CatalogEntry("Anal chastity", "Plug worn under access restriction."),
            CatalogEntry("Body worship"),
            CatalogEntry("Cock worship"),
            CatalogEntry("Pussy worship"),
            CatalogEntry("Foot worship"),
            CatalogEntry("Ass worship"),
            CatalogEntry("Goddess worship"),
            CatalogEntry("Muscle worship"),
            CatalogEntry("Boot worship"),
            CatalogEntry("Boot licking"),
            CatalogEntry("Boot blacking", "Cleaning a partner's boots as service."),
            CatalogEntry("Sensual / slave dances"),
            CatalogEntry("Slave bells", "Wearing bells as part of service / D/s aesthetic."),
            CatalogEntry("Slave tattoos", "Symbolic ownership tattoos."),
            CatalogEntry("Total Power Exchange (TPE)"),
            CatalogEntry("Internal Enslavement", "Mind-based total surrender."),
            CatalogEntry("Sexual slavery (consensual roleplay)"),
            CatalogEntry("Old Guard slavery", "Traditional leather/Old Guard protocols."),
            CatalogEntry("Being physically overpowered"),
        ],
    ),
    CatalogCategory(
        id="bondage_restraint",
        label="Bondage & Restraint",
        description="Tying, confining, and immobilizing.",
        items=[
            CatalogEntry("Bondage (general)"),
            CatalogEntry("Light bondage"),
            CatalogEntry("Rope bondage"),
            CatalogEntry("Shibari", "Japanese rope bondage tradition."),
            CatalogEntry("Hojojutsu", "Older Japanese tactical-rope tradition."),
            CatalogEntry("Suspension bondage"),
            CatalogEntry("Self-bondage"),
            CatalogEntry("Mental bondage", "Bound by rules and command, not rope."),
            CatalogEntry("Covert bondage", "Restraint worn under regular clothes in public."),
            CatalogEntry("Outdoor bondage"),
            CatalogEntry("Predicament bondage", "Restraint that forces a choice between two uncomfortable positions."),
            CatalogEntry("Hair bondage"),
            CatalogEntry("Breast bondage"),
            CatalogEntry("Scarf bondage"),
            CatalogEntry("Waterbondage", "Restraint involving water."),
            CatalogEntry("Handcuffs"),
            CatalogEntry("Shackles"),
            CatalogEntry("Chains"),
            CatalogEntry("Spreader bars"),
            CatalogEntry("Cling film / saran wrap"),
            CatalogEntry("Duct tape"),
            CatalogEntry("Bondage tape"),
            CatalogEntry("Mummification"),
            CatalogEntry("Sleepsacks"),
            CatalogEntry("Vacuum bed"),
            CatalogEntry("Zentai", "Full-body skintight suit."),
            CatalogEntry("Encasement"),
            CatalogEntry("Caging / confinement"),
            CatalogEntry("Armbinders"),
            CatalogEntry("Posture collars"),
            CatalogEntry("Collars and leash"),
            CatalogEntry("Hoods"),
            CatalogEntry("Masks"),
            CatalogEntry("Gas masks"),
            CatalogEntry("Gags"),
            CatalogEntry("Ball gags"),
        ],
    ),
    CatalogCategory(
        id="impact_discipline",
        label="Impact & Discipline",
        description="Hitting, striking, and structured punishment scenes.",
        items=[
            CatalogEntry("Spanking"),
            CatalogEntry("Bare-bottom spanking"),
            CatalogEntry("Bare-handed spanking"),
            CatalogEntry("OTK spanking", "Over-the-knee spanking."),
            CatalogEntry("Hairbrush spanking"),
            CatalogEntry("Belt spanking"),
            CatalogEntry("Belt whippings"),
            CatalogEntry("Paddling"),
            CatalogEntry("Caning"),
            CatalogEntry("Whipping"),
            CatalogEntry("Bullwhips"),
            CatalogEntry("Single-tail whips"),
            CatalogEntry("Flogging"),
            CatalogEntry("Riding crops"),
            CatalogEntry("Slapping"),
            CatalogEntry("Face slapping"),
            CatalogEntry("Tit slapping"),
            CatalogEntry("Cock slapping"),
            CatalogEntry("Pussy spanking"),
            CatalogEntry("Clit spanking"),
            CatalogEntry("Breast spanking"),
            CatalogEntry("Breast whipping"),
            CatalogEntry("Punching play"),
            CatalogEntry("Kicking"),
            CatalogEntry("Trampling"),
            CatalogEntry("Manhandling", "Rough physical handling."),
            CatalogEntry("Corporal punishment"),
            CatalogEntry("Punishment", "Punishment within an established D/s frame."),
            CatalogEntry("Play punishment", "Faux-punishment for fun."),
            CatalogEntry("Impact play (general)"),
        ],
    ),
    CatalogCategory(
        id="sensation_toys",
        label="Sensation, Toys & Equipment",
        description="Hardware-driven sensation: toys, machines, clamps, and electrical play.",
        items=[
            CatalogEntry("Sex toys (general)"),
            CatalogEntry("Dildos"),
            CatalogEntry("Glass dildos"),
            CatalogEntry("Vibrators"),
            CatalogEntry("Strap-ons", "The toy itself; for the act, see Pegging."),
            CatalogEntry("Sybian", "A powerful saddle vibrator."),
            CatalogEntry("Fucking machines"),
            CatalogEntry("Anal beads"),
            CatalogEntry("Butt plugs"),
            CatalogEntry("Anal hooks"),
            CatalogEntry("Ben Wa balls"),
            CatalogEntry("Inflatable toys"),
            CatalogEntry("Large objects", "Oversized insertions."),
            CatalogEntry("Vaginal stretching"),
            CatalogEntry("Anal stretching"),
            CatalogEntry("Anal training"),
            CatalogEntry("Vaginal fisting"),
            CatalogEntry("Anal fisting"),
            CatalogEntry("Cock milking"),
            CatalogEntry("Prostate massage"),
            CatalogEntry("Prostate milking"),
            CatalogEntry("Sounding", "Insertion of a rod into the urethra."),
            CatalogEntry("Speculums"),
            CatalogEntry("Catheters"),
            CatalogEntry("Medieval devices", "Vintage / antique-style hardware."),
            CatalogEntry("Remote-control devices"),
            CatalogEntry("Wax play"),
            CatalogEntry("Pussy pumping"),
            CatalogEntry("Clit pumping"),
            CatalogEntry("Vacuum pumping"),
            CatalogEntry("Cupping", "Vacuum suction cups."),
            CatalogEntry("Clamps and clips"),
            CatalogEntry("Nipple clamps"),
            CatalogEntry("Clover clamps"),
            CatalogEntry("Clothespins", "Improvised clamps."),
            CatalogEntry("Wartenberg pinwheels", "Spiked-wheel sensation tool."),
            CatalogEntry("Vampire gloves", "Spiked gloves."),
            CatalogEntry("E-Stim", "Electrical stimulation devices."),
            CatalogEntry("TENS unit"),
            CatalogEntry("Electrical play (general)"),
            CatalogEntry("Violet wand", "High-voltage low-current sparking device."),
            CatalogEntry("Ball stretching"),
            CatalogEntry("Toy making", "Making your own gear."),
        ],
    ),
    CatalogCategory(
        id="humiliation_degradation",
        label="Humiliation & Degradation",
        description="Verbal and social humiliation as scene texture. Always negotiated.",
        items=[
            CatalogEntry("Humiliation"),
            CatalogEntry("Verbal humiliation and degradation"),
            CatalogEntry("Degradation"),
            CatalogEntry("Defilement"),
            CatalogEntry("Public humiliation"),
            CatalogEntry("Female humiliation"),
            CatalogEntry("Cuckold humiliation"),
            CatalogEntry("Small-penis humiliation"),
            CatalogEntry("Slut play", "Verbal slut framing."),
            CatalogEntry("Bimboification", "Roleplay around becoming a 'bimbo' archetype."),
            CatalogEntry("Objectification"),
            CatalogEntry("Sexual objectification"),
            CatalogEntry("Toilet slave"),
            CatalogEntry("Human toilet"),
            CatalogEntry("Human ashtray"),
        ],
    ),
    CatalogCategory(
        id="body_fluids_functions",
        label="Body Fluids & Functions",
        description="Bodily fluids and biological functions used as part of a scene.",
        items=[
            CatalogEntry("Cum"),
            CatalogEntry("Creampie"),
            CatalogEntry("Anal creampie"),
            CatalogEntry("Creampie cleanup"),
            CatalogEntry("Facials", "Cum on the face."),
            CatalogEntry("Being cummed on"),
            CatalogEntry("Swallowing cum"),
            CatalogEntry("Squirting", "Female ejaculation."),
            CatalogEntry("Lactation"),
            CatalogEntry("Adult breastfeeding"),
            CatalogEntry("Spitting"),
            CatalogEntry("Sweat"),
            CatalogEntry("Tears", "Crying as part of a scene (dacryphilia)."),
            CatalogEntry("Watersports", "Urine play."),
            CatalogEntry("Toilet play"),
            CatalogEntry("Enemas"),
            CatalogEntry("Douching"),
            CatalogEntry("Diapers"),
            CatalogEntry("Face farting"),
            CatalogEntry("Panty-sniffing"),
        ],
    ),
    CatalogCategory(
        id="lifestyles_identity",
        label="Roleplay Lifestyles & Identity Play",
        description="Persistent persona play: petplay, age play, sissy, gender play, and other identity-shifting scenes.",
        items=[
            CatalogEntry("Cross-dressing"),
            CatalogEntry("Feminization"),
            CatalogEntry("Sissification"),
            CatalogEntry("Sissy training"),
            CatalogEntry("Sissy panties"),
            CatalogEntry("Gender play"),
            CatalogEntry("Transformation"),
            CatalogEntry("Dollification", "Treating partner as a doll."),
            CatalogEntry("Human doll"),
            CatalogEntry("Forniphilia", "Human furniture."),
            CatalogEntry("Pet play"),
            CatalogEntry("Puppy play"),
            CatalogEntry("Kitten petplay"),
            CatalogEntry("Pony play"),
            CatalogEntry("Wolfplay", "Wolf-themed petplay."),
            CatalogEntry("Piggy play", "Pig-themed petplay."),
            CatalogEntry("Furry"),
            CatalogEntry("Age play", "Roleplaying an age different from your own."),
            CatalogEntry("Infantilism"),
            CatalogEntry("ABDL", "Adult Baby / Diaper Lover."),
            CatalogEntry("DDlg", "Daddy Dom / little girl."),
            CatalogEntry("Mommy / boy"),
            CatalogEntry("Mommy / girl"),
            CatalogEntry("Gor", "Gorean lifestyle."),
            CatalogEntry("Gorean slave positions"),
            CatalogEntry("1950s household", "Mid-century gender-role lifestyle play."),
            CatalogEntry("Victorian lifestyle"),
        ],
    ),
    CatalogCategory(
        id="spiritual_energy",
        label="Spiritual & Energy Play",
        description="Esoteric and ritual frames around sex and intimacy.",
        items=[
            CatalogEntry("Tantra"),
            CatalogEntry("Sacred sexuality"),
            CatalogEntry("Sex magick"),
            CatalogEntry("Spiritual BDSM"),
            CatalogEntry("Chakra energy play"),
            CatalogEntry("Energy play"),
            CatalogEntry("Rituals"),
        ],
    ),
    CatalogCategory(
        id="pain_edge",
        label="Pain & Edge Play",
        description="Higher-risk sensation: pain, blood, fear, breath. Negotiate hard limits and risk explicitly.",
        items=[
            CatalogEntry("Pain"),
            CatalogEntry("Sadism"),
            CatalogEntry("Masochism"),
            CatalogEntry("Sadomasochism"),
            CatalogEntry("Edge play (general)"),
            CatalogEntry("Emotional sadism"),
            CatalogEntry("Emotional masochism"),
            CatalogEntry("CBT", "Cock and Ball Torture."),
            CatalogEntry("Ball kicking"),
            CatalogEntry("Ballbusting"),
            CatalogEntry("Bastinado", "Caning the soles of the feet."),
            CatalogEntry("Figging", "Insertion of a peeled ginger root."),
            CatalogEntry("Knife play"),
            CatalogEntry("Blood play"),
            CatalogEntry("Cutting", "Decorative or scene cutting."),
            CatalogEntry("Branding"),
            CatalogEntry("Scarification"),
            CatalogEntry("Needle play", "Including play piercing."),
            CatalogEntry("Fish hooks", "Hooks placed in skin."),
            CatalogEntry("Flesh hooks"),
            CatalogEntry("Hook suspension", "Suspension via flesh hooks."),
            CatalogEntry("Staples"),
            CatalogEntry("Corset piercing", "Pierced lacing across the back."),
            CatalogEntry("Fire play"),
            CatalogEntry("Fire cupping"),
            CatalogEntry("Fire flogging"),
            CatalogEntry("Breath play"),
            CatalogEntry("Choking play"),
            CatalogEntry("Asphyxiaphilia", "Erotic restriction of breath."),
            CatalogEntry("Smothering"),
            CatalogEntry("Waterboarding"),
            CatalogEntry("Mind fucks", "Psychological scene play."),
            CatalogEntry("Fear play"),
            CatalogEntry("Primal play", "Animalistic, instinct-driven scenes."),
            CatalogEntry("Bruises", "Marks left from impact."),
            CatalogEntry("Abrasion play", "Sandpaper or rough textures on skin."),
            CatalogEntry("Violence (general scene framing)"),
        ],
    ),
    CatalogCategory(
        id="taboo_fantasies",
        label="Taboo Fantasies",
        description="The most fantasy-only end of the catalogue — scenes that work as fiction between consenting adults but should be approached with explicit negotiation, hard limits, and clear safe words. Fantasy interest is not real-world consent.",
        items=[
            CatalogEntry("Pursuit, take-down & capture"),
            CatalogEntry("Predator / prey"),
            CatalogEntry("Abduction play"),
            CatalogEntry("Daddy / Daughter roleplay (consensual age-play between adults)"),
            CatalogEntry("Sister / Brother roleplay (consensual fantasy roleplay between adults)"),
            CatalogEntry("Race play", "Race-themed roleplay; negotiate with care."),
            CatalogEntry("Religious play"),
            CatalogEntry("Crucifixion play"),
            CatalogEntry("Military interrogation"),
            CatalogEntry("Mind control fantasy"),
            CatalogEntry("Breeding / impregnation fantasy"),
            CatalogEntry("Somnophilia (sleep play)", "Erotic play with a sleeping partner — pre-negotiated and consented."),
            CatalogEntry("Psycholagny", "Climax from purely mental stimulation."),
        ],
    ),
]


def _slugify(label: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", label.lower()).strip("_")
    return slug or "kink"


def _stable_id(category_id: str, label: str, used: set[str]) -> str:
    base = f"klib_{category_id}_{_slugify(label)}"
    candidate = base
    suffix = 2
    while candidate in used:
        candidate = f"{base}_{suffix}"
        suffix += 1
    used.add(candidate)
    return candidate


def categorized_kinks() -> list[dict[str, object]]:
    """Return categories with stable per-item ids. Each category dict has
    `id`, `label`, `description`, and `items: [{id, label, description}, ...]`.
    Order is preserved (vanilla -> edge)."""
    used: set[str] = set()
    out: list[dict[str, object]] = []
    for category in CATEGORIES:
        items_out: list[dict[str, str]] = []
        for entry in category.items:
            items_out.append({
                "id": _stable_id(category.id, entry.label, used),
                "label": entry.label,
                "description": entry.description,
            })
        out.append({
            "id": category.id,
            "label": category.label,
            "description": category.description,
            "items": items_out,
        })
    return out


def flat_kinks() -> list[dict[str, str]]:
    """Flat list of all entries across categories. Used by /api/kink-library."""
    flat: list[dict[str, str]] = []
    for category in categorized_kinks():
        for item in category["items"]:  # type: ignore[index]
            flat.append({
                "id": item["id"],
                "label": item["label"],
                "category": category["id"],  # type: ignore[index]
                "categoryLabel": category["label"],  # type: ignore[index]
                "description": item.get("description", ""),
            })
    return flat
